apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-server
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-server
  template:
    metadata:
      labels:
        app: ingestion-server
    spec:
      containers:
        - name: ingestion-server
          image: agentobs-ingestion-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: app-config
