apiVersion: v1
kind: Service
metadata:
  name: ingestion-server
  namespace: observability
spec:
  type: ClusterIP
  selector:
    app: ingestion-server
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
